---
apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-deployment-demo-controller-v1
spec:
  replicas: 4
  selector:
    app: k8s-deployment-demo
    version: v0.1
  template:
    metadata:
      labels:
        app: k8s-deployment-demo
        version: v0.1
    spec:
      containers:
        - name: k8s-deployment-demo
          image: ryane/k8s-deployment-demo:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: DEMO_ENV
              value: staging
